spring:
  application:
    name: Auth Service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all       # optional: ensures data durability
      retries: 3      # optional: retry on transient failure

    consumer:
      group-id: auth-service   # consumer group name
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"   # trust your event packages

    listener:
      concurrency: 3   # optional: allows multiple consumer threads


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:}:${MYSQL_PORT:}/${MYSQL_DB:}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username:
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jwt:
    secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    expiration-ms: 900000
    refresh-token:
      expiration-ms: 9000000000


server:
  port: 9898

logging:
  level:
    org.springframework.security: INFO
    your.package.name: INFO
